export const STRINGS = {
  appName: 'הבנק של אבא',
  login: {
    title: 'הבנק של אבא',
    subtitle: 'בחרו את החשבון שלכם',
    passwordPlaceholder: 'סיסמה',
    loginButton: 'כניסה',
    wrongPassword: 'סיסמה שגויה',
  },
  dashboard: {
    title: 'החיסכונות שלי',
    totalBalance: 'סך הכל',
    grewToday: 'הכסף שלך גדל היום ב-',
    newDeposit: 'הפקדה חדשה',
    recentTransactions: 'פעולות אחרונות',
    noDeposits: 'עדיין אין חיסכונות. בואו נתחיל!',
  },
  deposits: {
    flexible: 'גמיש',
    fixed: 'קבוע',
    interestRate: 'ריבית שנתית',
    principal: 'קרן',
    currentBalance: 'יתרה נוכחית',
    maturityDate: 'תאריך פדיון',
    daysLeft: 'ימים נותרו',
    status: {
      active: 'פעיל',
      matured: 'הבשיל',
      withdrawn: 'נפדה',
    },
    createTitle: 'הפקדה חדשה',
    depositName: 'שם החיסכון',
    depositNamePlaceholder: 'למשל: חיסכון לאופניים',
    amount: 'סכום',
    type: 'סוג חיסכון',
    termDays: 'תקופה (ימים)',
    create: 'צור חיסכון',
    withdraw: 'משיכה',
    withdrawConfirm: 'בטוח שרוצים למשוך?',
    withdrawPenalty: 'משיכה מוקדמת תגרום לקנס של',
    ofEarnedInterest: 'מהריבית שנצברה',
    penaltyAmount: 'סכום הקנס',
    youWillReceive: 'תקבלו',
    confirmWithdraw: 'אישור משיכה',
    cancel: 'ביטול',
  },
  transactions: {
    types: {
      deposit: 'הפקדה',
      withdrawal: 'משיכה',
      interest: 'ריבית',
      penalty: 'קנס',
      admin_adjustment: 'התאמת מנהל',
    },
  },
  admin: {
    title: 'ניהול',
    accounts: 'חשבונות',
    settings: 'הגדרות',
    createAccount: 'חשבון חדש',
    accountName: 'שם',
    password: 'סיסמה',
    avatar: 'אימוג\'י',
    save: 'שמירה',
    defaultFlexibleRate: 'ריבית ברירת מחדל - גמיש',
    defaultFixedRate: 'ריבית ברירת מחדל - קבוע',
    defaultPenalty: 'קנס משיכה מוקדמת',
    minDeposit: 'הפקדה מינימלית',
    allAccounts: 'כל החשבונות',
    totalInBank: 'סה"כ בבנק',
    adjustBalance: 'התאם יתרה',
    changeRate: 'שנה ריבית',
  },
  common: {
    loading: 'טוען...',
    error: 'שגיאה',
    back: 'חזרה',
    logout: 'יציאה',
  },
} as const;

export const AVATARS = ['🐷', '🦊', '🐰', '🐻', '🦁', '🐸', '🐱', '🐶', '🦄', '🐼', '🐨', '🦋'];
